services:
  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:delegated
      - ~/.bash_history:/home/sicp/.bash_history:delegated
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: ["make", "start-app"]

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:delegated
    depends_on:
      - database
      - application
    command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=300", "--sleep=3"]
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:delegated
    ports:
      - 5173:5173
    command: ["make", "start-frontend"]

  database:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54320:5432
    volumes:
      - hexlet-sicp-pgdata:/var/lib/postgresql/data

volumes:
  hexlet-sicp-pgdata:
